import "./globals.css";
import type { Metadata } from "next";
import { Plus_Jakarta_Sans } from "next/font/google";
import Providers from "../providers/Providers";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";

const plusjakartasans = Plus_Jakarta_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons: {
    icon: "/logo-mobile.png",
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${plusjakartasans.className} bg-light-main-bg dark:bg-dark-main-bg`}
      >
        <Providers>
          <ToastContainer
            pauseOnFocusLoss={false}
            bodyClassName="toast"
            autoClose={3000}
          />
          {children}
        </Providers>
      </body>
    </html>
  );
}
