import "./globals.css";
import type { Metadata } from "next";
import { Plus_Jakarta_Sans } from "next/font/google";
import Providers from "../providers/Providers";

const plusjakartasans = Plus_Jakarta_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${plusjakartasans.className} bg-light-main-bg dark:bg-dark-main-bg`}
      >
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
